### ISSUE TITLE
Errors running MCMD with an old version of Python

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-tools-commander#71]
I installed using pip on mac 10.14.2

First it wouldn't install because of existing 'six'. I run sudo -H pip install --ignore-installed six

Then I can install, and type mcmd --help.
I got following error
Traceback (most recent call last):
  File "/usr/local/bin/mcmd", line 9, in <module>
    load_entry_point('molgenis-commander==1.0.1', 'console_scripts', 'mcmd')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/mcmd/__main__.py", line 1, in <module>
    import logging
  File "/Library/Python/2.7/site-packages/mcmd/logging.py", line 7, in <module>
    logger = logging.getLogger('console')
AttributeError: 'module' object has no attribute 'getLogger'

**Comment by tommydeboer** [comment]
@mswertz Sadly, the default version of Python on MacOS is very old (2.7). We're developing for Python 3.6 and up. I'll see if we can do something about the feedback you get when installing with an old version.

**Comment by tommydeboer** [comment]
Requiring a certain Python version in the setup file sadly gives cryptic errors when installing with pip.

Best solution is to let the commander check at runtime if it's being run with the correct version.
